language: csharp
mono: none
solution: FeatuR.sln
sudo: required
dist: bionic
dotnet: 3.1.300

install:
  - dotnet restore
  
branches:
  only:
    - master
    - dev
    
before_script:
  - chmod -R a+x samples
  - chmod -R a+x scripts
  - chmod -R a+x src
  
script:
  - dotnet test ./test/FeatuR.Tests/FeatuR.Tests.csproj -c Release
  - dotnet build -c Release
  - ./scripts/pack.sh
  
notifications:
  email:
    on_success: never
    on_failure: always